-- 摇摆志 v2 数据库迁移
-- 在 Supabase SQL Editor 中执行

ALTER TABLE decisions
  ADD COLUMN IF NOT EXISTS hesitation INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS confidence INTEGER DEFAULT 0,
  ADD COLUMN IF NOT EXISTS notes TEXT DEFAULT '',
  ADD COLUMN IF NOT EXISTS is_favorite BOOLEAN DEFAULT FALSE;
